version: "3.8"

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=False
    networks:
      - appnet
      - traefik-public
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.charlie.rule=Host(`charlie.192.168.101.100.nip.io`)"
        - "traefik.http.routers.charlie.entrypoints=web"
        - "traefik.http.services.charlie.loadbalancer.server.port=8080"
  ollama:
    image: ollama/ollama:latest
    networks:
      - appnet
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:

networks:
  appnet:
    driver: overlay
  traefik-public:
    external: true
