version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__server__ROOT_URL=http://charlie.apps.lan/
    depends_on:
      - db
    volumes:
      - gitea_data:/data
    networks:
      - appnet
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.charlie.rule=Host(`charlie.apps.lan`)"
        - "traefik.http.routers.charlie.entrypoints=web"
        - "traefik.http.services.charlie.loadbalancer.server.port=3000"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - gitea_db:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  gitea_data:
  gitea_db:

networks:
  appnet:
    driver: overlay
  traefik-public:
    external: true
