version: "3.8"

services:
  traefik:
    image: traefik:v3.5
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=false"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik-public"
      - "--entrypoints.web.address=:80"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # Optionnel: exposer un ping pour healthcheck
        - "traefik.http.routers.traefik-ping.rule=Path(`/ping`)"
        - "traefik.http.routers.traefik-ping.entrypoints=web"
        - "traefik.http.services.traefik-ping.loadbalancer.server.port=8080"

  dns:
    image: coredns/coredns:latest
    command: ["-conf", "/Corefile"]
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
    networks:
      - traefik-public
    configs:
      - source: coredns-corefile
        target: /Corefile
      - source: coredns-zone-apps-lan
        target: /apps.lan.db
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  traefik-public-certificates:

configs:
  coredns-corefile:
    file: ./coredns/Corefile
  coredns-zone-apps-lan:
    file: ./coredns/apps.lan.db

networks:
  traefik-public:
    external: true
